ResolutionTracker/ViewModels/Common/ResolutionChangeModel.cs
namespace ResolutionTracker.ViewModels.Common
{
    public abstract class ResolutionChangeModel
    {
        public string ResolutionId { get; set; }

        public string ResolutionTitle { get; set; }

        public string ResolutionDescription { get; set; }

        public string ResolutionDeadline { get; set; }

        public string ResolutionType { get; set; }

        public string PercentageCompletion { get; set; }

        public string MusicGenre { get; set; }

        public string MusicalInstrument { get; set; }

        public string HealthArea { get; set; }

        public string CodingTechnology { get; set; }

        public string Language { get; set; }

        public string LanguageSkill { get; set; }
    }
}

ResolutionTracker/ViewModels/ResolutionCreateModel.cs
using ResolutionTracker.ViewModels.Common;

namespace ResolutionTracker.ViewModels
{
    public class ResolutionCreateModel : ResolutionChangeModel
    {
        
    }
}

ResolutionTracker/ViewModels/ResolutionDetailModel.cs
namespace ResolutionTracker.ViewModels
{
    public class ResolutionDetailModel
    {
        public string ResolutionId { get; set; }

        public string ResolutionTitle { get; set; }

        public string ResolutionDescription { get; set; }

        public string ResolutionDeadline { get; set; }

        public string ResolutionType { get; set; }

        public string PercentageCompletion { get; set; }

        public string PercentageLeft { get; set; }

        public bool ResolutionIsComplete { get; set; }

        public string DateCompleted { get; set; }

        public string MusicGenre { get; set; }

        public string MusicalInstrument { get; set; }

        public string HealthArea { get; set; }

        public string CodingTechnology { get; set; }

        public string Language { get; set; }

        public string LanguageSkill { get; set; }
    }
}

ResolutionTracker/ViewModels/ResolutionEditModel.cs
using ResolutionTracker.ViewModels.Common;

namespace ResolutionTracker.ViewModels
{
    public class ResolutionEditModel : ResolutionChangeModel
    {
        public bool ResolutionIsComplete { get; set; }

        public string ResolutionDateCompleted { get; set; }
    }
}

ResolutionTracker/ViewModels/ResolutionIndexListingModel.cs
namespace ResolutionTracker.ViewModels
{
    public class ResolutionIndexListingModel
    {
        public string ResolutionId { get; set; }

        public string ResolutionTitle { get; set; }

        public bool ResolutionIsComplete { get; set; }

    }
}

ResolutionTracker/ViewModels/ResolutionIndexModel.cs
using System.Collections.Generic;

namespace ResolutionTracker.ViewModels
{
    public class ResolutionIndexModel
    {
        public IEnumerable<ResolutionIndexListingModel> Resolutions { get; set; }
    }
}

ResolutionTracker/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace ResolutionTracker.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

ResolutionTracker/Controllers/ResolutionController.cs
using System;
using System.Linq;
using System.Net;
using Microsoft.AspNetCore.Mvc;
using ResolutionTracker.Data.Models;
using ResolutionTracker.Data.Models.Common;
using ResolutionTracker.Services.Common;
using ResolutionTracker.ViewModels;

namespace ResolutionTracker.Controllers
{
    public class ResolutionController : Controller
    {
        private IResolutionService _resolutionService;

        public ResolutionController(IResolutionService resolutionService)
        {
            _resolutionService = resolutionService;
        }

        // root route
        [HttpGet]
        public IActionResult Index()
        {
            // have the service get what we need
            var resolutionIndexObject = _resolutionService.GetResolutionIndexObject();
            // then we pass this ResolutionIndexModel to the view
            return View(resolutionIndexObject);
        }

        // SHOW route
        [HttpGet]
        public IActionResult Detail(int id)
        {
            var currentResolutionDetailObject = _resolutionService.GetResolutionDetailObject(id);           
            return View(currentResolutionDetailObject);
        }

        // GET returns the default Create view which is the form
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        //   POST (how to protect against over posting attack?)
        // also make sure you sanitise the user inputs
        // to-do: add calendar to date input
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ResolutionCreateModel newViewResolution)
        {
            if (ModelState.IsValid)
            {
                var resolutionToAdd = _resolutionService.GetResolutionFromUserInput(newViewResolution);
                _resolutionService.CreateResolution(resolutionToAdd);
                return RedirectToAction("Index");
            }
            else
            {
                return View(newViewResolution);
            }
        }

        // update
        // GET returns the default Edit view which is again the form
        [HttpGet]
        public IActionResult Edit(int id)
        {
            // get resolution to edit
            var viewResolutionToEdit = _resolutionService.GetResolutionEditObject(id);

            return viewResolutionToEdit == null ? View(new NotFoundResult()) : View(viewResolutionToEdit);
        }

        // UPDATE corresponds to Put. Put means you submit the whole object again when you update; Patch means you submit only certain deetz
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, ResolutionEditModel viewResolutionToEdit)
        {
            // finish this Put method
            if (ModelState.IsValid)
            {
                //reassign the values of the resolution's properties with the values we've received
                // in the view model
                var resolutionToUpdate = _resolutionService.GetResolutionToEdit(id, viewResolutionToEdit);
                _resolutionService.EditResolution(resolutionToUpdate);
                return RedirectToAction("Index");
            }
            else
            {
                return View(viewResolutionToEdit);
            }
        }







        //delete routes
    }
}

ResolutionTracker/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div>
    <h1 class="display-4 light-yellow">Welcome to Evie's New Year's Resolutions 2020!</h1>
</div>
<div>
    <a class="btn btn-lg btn-info" asp-controller="Resolution" asp-action="Index">View all resolutions</a>
    <a class="btn btn-lg btn-info" asp-controller="Resolution" asp-action="Create">Add new resolution</a>
</div>

ResolutionTracker/Views/Resolution/Create.cshtml
@model ResolutionTracker.ViewModels.ResolutionCreateModel

@{
    ViewData["Title"] = "New Resolution";
}

    <div class="resolution-form light-green">
        <h1>Make a New Resolution!</h1>
        <form asp-action="Create" method="POST">
            <div class="form-group">
                <input type="text" name="ResolutionTitle" class="form-control" placeholder="Title" asp-for="ResolutionTitle">
            </div>
            <div class="form-group">
                <input type="text" name="ResolutionDescription" class="form-control" placeholder="Description" asp-for="ResolutionDescription">
            </div>
            <div class="form-group">
                <input type="text" name="ResolutionDeadline" class="form-control" placeholder="Deadline" asp-for="ResolutionDeadline">
            </div>
            <div class="form-group">
                <select name="ResolutionType" class="form-control" asp-for="ResolutionType">
                    <option selected disabled>Select resolution type...</option>
                    <option>Music</option>
                    <option>Health</option>
                    <option>Coding</option>
                    <option>Language</option>
                </select>
            </div>
            <div class="form-group">
                <input type="text" name="PercentageCompletion" class="form-control" placeholder="Percentage Completion" asp-for="PercentageCompletion">
            </div>
            <button type="submit"class="btn btn-primary">Submit</button>
        </form>
    </div>




ResolutionTracker/Views/Resolution/Detail.cshtml
@model ResolutionTracker.ViewModels.ResolutionDetailModel

@{
    ViewData["Title"] = $"{Model.ResolutionTitle}";
}

<h1 class="light-green">@Model.ResolutionTitle</h1>
<div class="progress">
    <div class="progress-bar progress-bar-striped bg-info" role="progressbar" style="width: @Model.PercentageCompletion%" aria-valuenow="{@Model.PercentageCompletion}" aria-valuemin="0" aria-valuemax="100">@Model.PercentageCompletion%</div>
</div>
<hr class="white-background"/>
<div class="main-details">
    <p>@Model.ResolutionDescription</p>
    <p>Category: @Model.ResolutionType</p>
    @{
        if (Model.ResolutionType.ToLower().Equals("music"))
        {
            <p>Instrument: @Model.MusicalInstrument</p>
            <p>Genre: @Model.MusicGenre</p>
        }
        else if (Model.ResolutionType.ToLower().Equals("health"))
        {
            <p>Keep your @Model.HealthArea healthy!</p>
        }
        else if (Model.ResolutionType.ToLower().Equals("coding"))
        {
            <p>This will help you practise @Model.CodingTechnology</p>
        }
        else
        {
            <p>What a lush way to practise your @Model.Language @Model.LanguageSkill!</p>
        }

        if (!Model.ResolutionIsComplete)
        {
            <p>Percentage left to complete by @Model.ResolutionDeadline: @Model.PercentageLeft%</p>
        }
    }
    <a asp-action="Edit" asp-route-id="@Model.ResolutionId">Edit</a>
    <a asp-action="Delete" asp-route-id="@Model.ResolutionId">Delete</a>
</div>
<a class="btn btn-lg btn-info" asp-controller="Resolution" asp-action="Index">Back to all resolutions</a>

ResolutionTracker/Views/Resolution/Edit.cshtml
@model ResolutionTracker.ViewModels.ResolutionEditModel

@{ 
    ViewData["Title"] = $"Edit {Model.ResolutionTitle} resolution";
}

    <div class="resolution-form light-yellow">
        <h1>Edit @Model.ResolutionTitle.  Id is @Model.ResolutionId</h1>
        @Html.HiddenFor(Model => Model.ResolutionId)
    <form asp-action="Edit" method="POST" asp-route-id="@Model.ResolutionId">
        <div class="form-group">
            <input type="text" name="ResolutionTitle" class="form-control" placeholder="Title" asp-for="ResolutionTitle">
        </div>
        <div class="form-group">
            <input type="text" name="ResolutionDescription" class="form-control" placeholder="Description" asp-for="ResolutionDescription">
        </div>
        <div class="form-group">
            <input type="text" name="ResolutionDeadline" class="form-control" placeholder="Deadline" asp-for="ResolutionDeadline">
        </div>
        <div class="form-group">
            <p>Is this resolution complete?</p>
            <input type="checkbox" name="ResolutionIsComplete" class="form-control" asp-for="ResolutionIsComplete">
        </div>
        @{
            if (Model.ResolutionIsComplete)
            {
                <div class="form-group">
                    <input type="text" name="ResolutionDateCompleted" class="form-control" placeholder="Date Completed" asp-for="ResolutionDateCompleted">
                </div>  
            }
        }
        <div class="form-group">
            <select name="ResolutionType" class="form-control" asp-for="ResolutionType">
                <option selected disabled>Select resolution type...</option>
                <option>Music</option>
                <option>Health</option>
                <option>Coding</option>
                <option>Language</option>
            </select>
        </div>
        <div class="form-group">
            <input type="text" name="PercentageCompletion" class="form-control" placeholder="Percentage Completion" asp-for="PercentageCompletion">
        </div>
        @{
            var resolutionType = Model.ResolutionType.ToLower();
            switch (resolutionType)
            {
                case "music":
                    <div class="form-group">
                        <input type="text" name="MusicGenre" class="form-control" placeholder="Music Genre" asp-for="MusicGenre">
                    </div>
                    <div class="form-group">
                        <input type="text" name="MusicalInstrument" class="form-control" placeholder="Musical Instrument" asp-for="MusicalInstrument">
                    </div>
                    break;
                case "health":
                    <div class="form-group">
                        <input type="text" name="HealthArea" class="form-control" placeholder="Health Area" asp-for="HealthArea">
                    </div>
                    break;
                case "coding":
                    <div class="form-group">
                        <input type="text" name="CodingTechnology" class="form-control" placeholder="Coding Technology" asp-for="CodingTechnology">
                    </div>
                    break;
                case "language":
                    <div class="form-group">
                        <input type="text" name="Language" class="form-control" placeholder="Language" asp-for="Language">
                    </div>
                    <div class="form-group">
                        <input type="text" name="LanguageSkill" class="form-control" placeholder="Language Skill" asp-for="LanguageSkill">
                    </div>
                    break;
                default:
                    <p>Looks like this resolution doesn't have a type yet...</p>
                    break;
            }
        }
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
    </div>

ResolutionTracker/Views/Resolution/Index.cshtml
@model ResolutionTracker.ViewModels.ResolutionIndexModel

@{
    ViewData["Title"] = "All Resolutions";
}

<div class="row title-section">
    <div class="col-lg-12 light-green">
        <h2>Evie's New Year's Resolutions 2020</h2>
        <h3>The date is @DateTime.Now</h3>
    </div>
</div>
<div class="row text-center">
    @foreach (var resolution in Model.Resolutions)
    {
        <div class="col-md-3 col-sm-6">
            <div class="thumbnail resolution-square">
                <div class="caption">
                    <h4 class="light-yellow">@resolution.ResolutionTitle</h4>
                    <a asp-controller="Resolution" asp-action="Detail" asp-route-id="@resolution.ResolutionId" class="btn btn-primary">More Info</a>
                </div>
            </div>
        </div>
    }
</div>

ResolutionTracker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Resolution Tracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?family=Inconsolata&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand light-green" asp-area="" asp-controller="Home" asp-action="Index">Resolution Tracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 light-yellow">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Resolution Tracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>